config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # /pokemon/:id/image.png
  resources :pokemons do
    member do
      get :image
    end
  end

  root 'home#index'
  get 'home/contact'
  post 'request_contact', to: 'home#request_contact'
 
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/egg_group.rb
class EggGroup < ApplicationRecord
  belongs_to :pokemon
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  has_one_attached :pokemon_image
  has_many :egg_groups
  has_many :pokemon_species
end

app/models/pokemon_specy.rb
class PokemonSpecy < ApplicationRecord
  belongs_to :pokemon
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @pokemons = Pokemon.all
  end

  def contact
  end 
  
  def request_contact
    name = params[:name]
    email = params[:email]
    telephone = params[:telephone]
    message = params[:message]
    
    if email.blank?
      flash[:alert] = I18n.t('home.request_contact.no_email')
    else
      ContactMailer.contact_email(email, name, telephone, message).deliver_now
      flash[:notice] = I18n.t('home.request_contact.email_sent')
    end
    redirect_back fallback_location: root_url
  end
    
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  before_action :set_pokemon, only: %i[ show edit update destroy ]

  # GET /pokemons or /pokemons.json
  def index
    @pokemons = Pokemon.all
  end

  # GET /pokemons/1 or /pokemons/1.json
  def show
  end

  def image
    @pokemon = Pokemon.find(params[:id])

    send_data @pokemon.image, :type => 'image/png',:disposition => 'inline'
  end

  # GET /pokemons/new
  def new
    @pokemon = Pokemon.new
  end

  # GET /pokemons/1/edit
  def edit
  end

  # POST /pokemons or /pokemons.json
  def create
    @pokemon = Pokemon.new(pokemon_params)

    respond_to do |format|
      if @pokemon.save
        format.html { redirect_to @pokemon, notice: "Pokemon was successfully created." }
        format.json { render :show, status: :created, location: @pokemon }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pokemons/1 or /pokemons/1.json
  def update
    respond_to do |format|
      if @pokemon.update(pokemon_params)
        format.html { redirect_to @pokemon, notice: "Pokemon was successfully updated." }
        format.json { render :show, status: :ok, location: @pokemon }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pokemons/1 or /pokemons/1.json
  def destroy
    @pokemon.destroy
    respond_to do |format|
      format.html { redirect_to pokemons_url, notice: "Pokemon was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pokemon
      @pokemon = Pokemon.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pokemon_params
      params.require(:pokemon).permit(:name, :image, :index, :gen)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/views/home/_footer.html.haml
#footer-container
  %footer
    %p Copyright © 2019  | All Rights Reserved.

app/views/home/_header.html.haml
%nav.nav
  %ul.nav__list
    %li.nav__listitem
      %svg.h-5.w-5{:fill => "currentColor", :viewbox => "0 0 20 20", :xmlns => "http://www.w3.org/2000/svg"}
        %path{"clip-rule" => "evenodd", :d => "M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z", "fill-rule" => "evenodd"}
      %ul.nav__listitemdrop
        %li= link_to 'Admin', new_admin_user_session_url
        %li= link_to 'Contact', home_contact_url
    %li.nav__listitem
      %h1= link_to 'Pokedex', root_path

app/views/home/contact.html.haml
.container
  = form_tag request_contact_path, method: 'post', id:"contact" do
    .titleH
      %h2 Quick Contact
    %script
    %fieldset
      =text_field_tag :name,'',autofocus: "", placeholder: "Your Name", required: "", tabindex: "1"
    %fieldset
      =text_field_tag :email,'',autofocus: "", placeholder: "Your Email", required: "", tabindex: "2"
    %fieldset
      =text_field_tag :telephone,'',autofocus: "", placeholder: "Your Telephone", required: "", tabindex: "3"
    %fieldset
      =text_area_tag :message,'',autofocus: "", placeholder: "Your Message", required: "", tabindex: "4"
    %fieldset
      %button#contact-submit{"data-submit" => "...Sending", :name => "submit", :type => "submit"} Submit 

app/views/home/index.html.haml
.main
  %ul.cards
    - @pokemons.each do |pokemon|
      %li.cards_item
        .card
          - if pokemon.pokemon_type == 'grass' || pokemon.pokemon_type == 'Grass'
            - backtype1 = 'card_image1'
          - elsif pokemon.pokemon_type == 'water' || pokemon.pokemon_type == 'Water'
            - backtype1 = 'card_image3'
          - elsif pokemon.pokemon_type == 'Fire' || pokemon.pokemon_type == 'fire'
            - backtype1 = 'card_image2'
          - else
            - backtype1 = 'card_image5'
          %div{class: backtype1}
            - pokemon
            - if pokemon.pokemon_image.present?
              = link_to pokemon_path(pokemon) do
                = image_tag pokemon.pokemon_image, class: "card-img-top"
          .card_text
            %h2.card_title= pokemon.name
            %p.card_text= pokemon.description
            %button.btn.card_btn= link_to 'Read More', pokemon_path(pokemon)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title WebCW
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    %script{:crossorigin => "anonymous", :integrity => "sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=", :src => "https://code.jquery.com/jquery-3.6.0.js"}
    %link{:href => "https://fonts.googleapis.com/css?family=Dosis", :rel => "stylesheet"}/
  %body

    = render 'home/header'

    - flash.each do |key, value|
      = content_tag :div, content_tag(:p, value), id: "#{key}" unless value.blank?

    = yield
    
    = render 'home/footer'

app/views/pokemons/show.html.haml
- if @pokemon.pokemon_type == 'grass' || @pokemon.pokemon_type == 'Grass'
  - backtype1 = 'card_image1'
- elsif @pokemon.pokemon_type == 'water' || @pokemon.pokemon_type == 'Water'
  - backtype1 = 'card_image3'
- elsif @pokemon.pokemon_type == 'Fire' || @pokemon.pokemon_type == 'fire'
  - backtype1 = 'card_image2'
- else
  - backtype1 = 'card_image5'
%p#notice= notice
.main
  .cardDesc{class: backtype1}
   
    %p
      = image_tag @pokemon.pokemon_image
    %div.titleDesc
      %p= @pokemon.name
      %p= "##{@pokemon.id}"
  .card_content
    %p.card_textDesc
      %strong Description:
      = @pokemon.description
    %p.card_textDesc
      %strong Elements:
      = @pokemon.species
    %p.card_textDesc
      %strong Height:
      = @pokemon.height
    %p.card_textDesc
      %strong Weight:
      = @pokemon.weight
    %p.card_textDesc
      %strong Abilities:
      = @pokemon.abilities
    %p.card_textDesc
      %strong Egg Cycle:
      = @pokemon.egg_cycle
  / <p>
  / <strong>pokemon_type:</strong>
  / </p>